[project]
name = "algorithm-trading"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "fyers-apiv3",
    "matplotlib>=3.7.0",
    "python-dotenv>=1.0.0",
    "scipy>=1.11.0"
]
